// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xexnijltsjlbihwmenqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhleG5pamx0c2psYmlod21lbnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzgxOTAsImV4cCI6MjA3MDI1NDE5MH0.rocpzZWF11R3FTKTk0aUgAkGSbMJrplfSC69Un7hjFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});